// Map country names (as used in the matches table) to ISO 3166-1 alpha-2 codes
// for use with https://flagsapi.com/{code}/flat/64.png
const countryCodeMap: Record<string, string> = {
  // Group A
  'Marrocos': 'MA',
  'Morocco': 'MA',
  'Estados Unidos': 'US',
  'USA': 'US',
  'United States': 'US',
  'EUA': 'US',

  // Group B
  'Portugal': 'PT',
  'Espanha': 'ES',
  'Spain': 'ES',

  // Group C
  'Argentina': 'AR',
  'México': 'MX',
  'Mexico': 'MX',

  // Group D
  'Dinamarca': 'DK',
  'Denmark': 'DK',
  'Indonésia': 'ID',
  'Indonesia': 'ID',

  // Group E
  'Alemanha': 'DE',
  'Germany': 'DE',
  'Itália': 'IT',
  'Italy': 'IT',

  // Group F
  'Brasil': 'BR',
  'Brazil': 'BR',
  'Colômbia': 'CO',
  'Colombia': 'CO',

  // Group G
  'França': 'FR',
  'France': 'FR',

  // Group H
  'Japão': 'JP',
  'Japan': 'JP',
  'Sérvia': 'RS',
  'Serbia': 'RS',

  // Group I
  'Irã': 'IR',
  'Iran': 'IR',
  'Coreia do Sul': 'KR',
  'South Korea': 'KR',

  // Group J
  'Uruguai': 'UY',
  'Uruguay': 'UY',
  'Bolívia': 'BO',
  'Bolivia': 'BO',

  // Group K
  'Equador': 'EC',
  'Ecuador': 'EC',
  'Camarões': 'CM',
  'Cameroon': 'CM',

  // Group L
  'Nigéria': 'NG',
  'Nigeria': 'NG',
  'Tunísia': 'TN',
  'Tunisia': 'TN',

  // Other teams
  'África do Sul': 'ZA',
  'South Africa': 'ZA',
  'Cabo Verde': 'CV',
  'Cape Verde': 'CV',
  'Congo': 'CD',
  'Austrália': 'AU',
  'Australia': 'AU',
  'Gana': 'GH',
  'Ghana': 'GH',
  'Senegal': 'SN',
  'Egito': 'EG',
  'Egypt': 'EG',
  'Canadá': 'CA',
  'Canada': 'CA',
  'Costa Rica': 'CR',
  'Panamá': 'PA',
  'Panama': 'PA',
  'Paraguai': 'PY',
  'Paraguay': 'PY',
  'Peru': 'PE',
  'Chile': 'CL',
  'Venezuela': 'VE',
  'Honduras': 'HN',
  'Jamaica': 'JM',
  'Arábia Saudita': 'SA',
  'Saudi Arabia': 'SA',
  'Qatar': 'QA',
  'Catar': 'QA',
  'Croácia': 'HR',
  'Croatia': 'HR',
  'Holanda': 'NL',
  'Netherlands': 'NL',
  'Países Baixos': 'NL',
  'Bélgica': 'BE',
  'Belgium': 'BE',
  'Suíça': 'CH',
  'Switzerland': 'CH',
  'Polônia': 'PL',
  'Poland': 'PL',
  'País de Gales': 'GB-WLS',
  'Wales': 'GB-WLS',
  'Inglaterra': 'GB-ENG',
  'England': 'GB-ENG',
  'Escócia': 'GB-SCT',
  'Scotland': 'GB-SCT',
  'Turquia': 'TR',
  'Turkey': 'TR',
  'Ucrânia': 'UA',
  'Ukraine': 'UA',
  'Rússia': 'RU',
  'Russia': 'RU',
  'Suécia': 'SE',
  'Sweden': 'SE',
  'Noruega': 'NO',
  'Norway': 'NO',
  'Áustria': 'AT',
  'Austria': 'AT',
  'República Tcheca': 'CZ',
  'Rep. Tcheca': 'CZ',
  'Czech Republic': 'CZ',
  'Eslováquia': 'SK',
  'Slovakia': 'SK',
  'Eslovênia': 'SI',
  'Slovenia': 'SI',
  'Romênia': 'RO',
  'Romania': 'RO',
  'Hungria': 'HU',
  'Hungary': 'HU',
  'Grécia': 'GR',
  'Greece': 'GR',
  'Albânia': 'AL',
  'Albania': 'AL',
  'Costa do Marfim': 'CI',
  'Ivory Coast': 'CI',
  'Mali': 'ML',
  'Argélia': 'DZ',
  'Algeria': 'DZ',
  'RD Congo': 'CD',
  'DR Congo': 'CD',
  'Burkina Faso': 'BF',
  'Guiné': 'GN',
  'Guinea': 'GN',
  'Moçambique': 'MZ',
  'Mozambique': 'MZ',
  'Tanzânia': 'TZ',
  'Tanzania': 'TZ',
  'Uganda': 'UG',
  'Iraque': 'IQ',
  'Iraq': 'IQ',
  'Uzbequistão': 'UZ',
  'Uzbekistan': 'UZ',
  'Jordânia': 'JO',
  'Jordan': 'JO',
  'Síria': 'SY',
  'Syria': 'SY',
  'Bahrein': 'BH',
  'Bahrain': 'BH',
  'China': 'CN',
  'Tailândia': 'TH',
  'Thailand': 'TH',
  'Vietnã': 'VN',
  'Vietnam': 'VN',
  'Nova Zelândia': 'NZ',
  'New Zealand': 'NZ',
  'Fiji': 'FJ',
  'Trinidad e Tobago': 'TT',
  'Trinidad and Tobago': 'TT',
  'El Salvador': 'SV',
  'Curaçao': 'CW',
  'Haiti': 'HT',
  'Guatemala': 'GT',
  'Bahamas': 'BS',
  'República Dominicana': 'DO',
  'Dominican Republic': 'DO',
  'Geórgia': 'GE',
  'Georgia': 'GE',
  'Islândia': 'IS',
  'Iceland': 'IS',
  'Irlanda': 'IE',
  'Ireland': 'IE',
  'Finlândia': 'FI',
  'Finland': 'FI',
  'Macedônia do Norte': 'MK',
  'North Macedonia': 'MK',
  'Montenegro': 'ME',
  'Bósnia': 'BA',
  'Bósnia e Herzegovina': 'BA',
  'Bosnia': 'BA',
  'Luxemburgo': 'LU',
  'Luxembourg': 'LU',
  'Cipro': 'CY',
  'Cyprus': 'CY',
  'Armênia': 'AM',
  'Armenia': 'AM',
  'Azerbaijão': 'AZ',
  'Azerbaijan': 'AZ',
  'Cazaquistão': 'KZ',
  'Kazakhstan': 'KZ',
  'Quirguistão': 'KG',
  'Kyrgyzstan': 'KG',
  'Palestina': 'PS',
  'Palestine': 'PS',
  'Omã': 'OM',
  'Oman': 'OM',
  'Líbano': 'LB',
  'Lebanon': 'LB',
  'Iêmen': 'YE',
  'Yemen': 'YE',
  'Coreia do Norte': 'KP',
  'North Korea': 'KP',
};

export function getCountryCode(name: string): string | null {
  return countryCodeMap[name] ?? null;
}

export function getFlagUrl(countryName: string, size: 16 | 24 | 32 | 48 | 64 = 32): string | null {
  const code = getCountryCode(countryName);
  if (!code) return null;
  // flagsapi.com doesn't support sub-national codes like GB-ENG, GB-SCT, GB-WLS
  // Use flagcdn.com for those
  if (code.startsWith('GB-')) {
    const sub = code.split('-')[1].toLowerCase();
    return `https://flagcdn.com/w${size}/${sub}.png`;
  }
  return `https://flagsapi.com/${code}/flat/${size}.png`;
}
